### ISSUE TITLE
partition file 'OP14_2region.mat' does not exist

### ISSUE THREAD

**Issue by sichu366** [guojunyao419/OPF-ADMM#1]
Hi Guojun Yao,

I am learning how to solve problems by ADMM. After reading your paper, I try to run the code.

However, it seems like the partition file is not added to your repository. Could you add it?

Best

**Comment by guojunyao419** [comment]
Thanks for posting the issue. I just uploaded the partition file. Please make sure that you've downloaded the pypower toolbox because I used some functions there.
